package com.ren.blog.model;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {

    private String firstCateName;
    private String secCataName;
    private String tagName;
    private String cataName;
    private String mdContent;

    public String getMdContent() {
        return mdContent;
    }

    public void setMdContent(String mdContent) {
        this.mdContent = mdContent;
    }

    public String getFirstCateName() {
        return firstCateName;
    }

    public void setFirstCateName(String firstCateName) {
        this.firstCateName = firstCateName;
    }

    public String getSecCataName() {
        return secCataName;
    }

    public void setSecCataName(String secCataName) {
        this.secCataName = secCataName;
    }

    public String getTagName() {
        return tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    public String getCataName() {
        return cataName;
    }

    public void setCataName(String cataName) {
        this.cataName = cataName;
    }


    private Integer articleId;


    private String articleName;


    private Long readCount;


    private Integer cataId;


    private String enable;


    private Date updateTime;


    private String updateBy;


    private Date createTime;


    private String createBy;


    private String title;


    private Integer subCataId;


    private String srcImage;


    private String content;


    private static final long serialVersionUID = 1L;


    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_name
     *
     * @return the value of article.article_name
     *
     * @mbggenerated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_name
     *
     * @param articleName the value for article.article_name
     *
     * @mbggenerated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.read_count
     *
     * @return the value of article.read_count
     *
     * @mbggenerated
     */
    public Long getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.read_count
     *
     * @param readCount the value for article.read_count
     *
     * @mbggenerated
     */
    public void setReadCount(Long readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.cata_id
     *
     * @return the value of article.cata_id
     *
     * @mbggenerated
     */
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.cata_id
     *
     * @param cataId the value for article.cata_id
     *
     * @mbggenerated
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.enable
     *
     * @return the value of article.enable
     *
     * @mbggenerated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.enable
     *
     * @param enable the value for article.enable
     *
     * @mbggenerated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_by
     *
     * @return the value of article.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_by
     *
     * @param updateBy the value for article.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_by
     *
     * @return the value of article.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_by
     *
     * @param createBy the value for article.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sub_cata_id
     *
     * @return the value of article.sub_cata_id
     *
     * @mbggenerated
     */
    public Integer getSubCataId() {
        return subCataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sub_cata_id
     *
     * @param subCataId the value for article.sub_cata_id
     *
     * @mbggenerated
     */
    public void setSubCataId(Integer subCataId) {
        this.subCataId = subCataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.src_image
     *
     * @return the value of article.src_image
     *
     * @mbggenerated
     */
    public String getSrcImage() {
        return srcImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.src_image
     *
     * @param srcImage the value for article.src_image
     *
     * @mbggenerated
     */
    public void setSrcImage(String srcImage) {
        this.srcImage = srcImage == null ? null : srcImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", articleName=").append(articleName);
        sb.append(", readCount=").append(readCount);
        sb.append(", cataId=").append(cataId);
        sb.append(", enable=").append(enable);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", title=").append(title);
        sb.append(", subCataId=").append(subCataId);
        sb.append(", srcImage=").append(srcImage);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}