package com.ren.blog.model;

import java.io.Serializable;

public class Cata implements Serializable {
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    private Integer count;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.cata_id
     *
     * @mbggenerated
     */
    private Integer cataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.cata_level
     *
     * @mbggenerated
     */
    private String cataLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.cata_name
     *
     * @mbggenerated
     */
    private String cataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.sub_cata_count
     *
     * @mbggenerated
     */
    private Integer subCataCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.sequence
     *
     * @mbggenerated
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.enable
     *
     * @mbggenerated
     */
    private String enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cata.parent_cata
     *
     * @mbggenerated
     */
    private Integer parentCata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cata
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.cata_id
     *
     * @return the value of cata.cata_id
     *
     * @mbggenerated
     */
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.cata_id
     *
     * @param cataId the value for cata.cata_id
     *
     * @mbggenerated
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.cata_level
     *
     * @return the value of cata.cata_level
     *
     * @mbggenerated
     */
    public String getCataLevel() {
        return cataLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.cata_level
     *
     * @param cataLevel the value for cata.cata_level
     *
     * @mbggenerated
     */
    public void setCataLevel(String cataLevel) {
        this.cataLevel = cataLevel == null ? null : cataLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.cata_name
     *
     * @return the value of cata.cata_name
     *
     * @mbggenerated
     */
    public String getCataName() {
        return cataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.cata_name
     *
     * @param cataName the value for cata.cata_name
     *
     * @mbggenerated
     */
    public void setCataName(String cataName) {
        this.cataName = cataName == null ? null : cataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.sub_cata_count
     *
     * @return the value of cata.sub_cata_count
     *
     * @mbggenerated
     */
    public Integer getSubCataCount() {
        return subCataCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.sub_cata_count
     *
     * @param subCataCount the value for cata.sub_cata_count
     *
     * @mbggenerated
     */
    public void setSubCataCount(Integer subCataCount) {
        this.subCataCount = subCataCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.sequence
     *
     * @return the value of cata.sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.sequence
     *
     * @param sequence the value for cata.sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.enable
     *
     * @return the value of cata.enable
     *
     * @mbggenerated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.enable
     *
     * @param enable the value for cata.enable
     *
     * @mbggenerated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cata.parent_cata
     *
     * @return the value of cata.parent_cata
     *
     * @mbggenerated
     */
    public Integer getParentCata() {
        return parentCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cata.parent_cata
     *
     * @param parentCata the value for cata.parent_cata
     *
     * @mbggenerated
     */
    public void setParentCata(Integer parentCata) {
        this.parentCata = parentCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cataId=").append(cataId);
        sb.append(", cataLevel=").append(cataLevel);
        sb.append(", cataName=").append(cataName);
        sb.append(", subCataCount=").append(subCataCount);
        sb.append(", sequence=").append(sequence);
        sb.append(", enable=").append(enable);
        sb.append(", parentCata=").append(parentCata);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}