package com.ren.blog.dao;

import com.ren.blog.model.Cata;
import java.util.List;
import java.util.Map;

public interface CataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    int insert(Cata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    Cata selectByPrimaryKey(Integer cataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    List<Cata> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cata record);

    List<Cata> getCataList(Cata cata);

    int saveOrUpdateCata(Cata record);
}